{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Select * From employees;\n",
    "Select * from salaries;\n",
    "\n",
    "--List the following details of each employee: employee number, last name, first name, sex, and salary.\n",
    "SELECT salaries.emp_no,\n",
    "\tsalaries.salary,\n",
    "\temployees.emp_no,\n",
    "\temployees.emp_title_id,\n",
    "\temployees.first_name,\n",
    "\temployees.last_name,\n",
    "\temployees.sex\n",
    " \tFROM employees, salaries\n",
    "\tWHERE salaries.emp_no = employees.emp_no;\n",
    "\t\n",
    "\n",
    "--List first name, last name, and hire date for employees who were hired in 1986.\n",
    "SELECT employees.first_name,\n",
    "\temployees.last_name,\n",
    "\temployees.hire_date\n",
    "\tFROM employees\n",
    "\tWHERE EXTRACT (year FROM employees.hire_date) = 1986\n",
    "\n",
    "\n",
    "--List the manager of each department with the following information: department number, \n",
    "--department name, the manager's employee number, last name, first name.\n",
    "Select department_manager.dept_no,\n",
    "\tdepartments.dept_name,\n",
    "\tdepartment_manager.emp_no, \n",
    "\temployees.last_name, \n",
    "\temployees.first_name\n",
    "FROM department_manager\n",
    "\tINNER JOIN departments \n",
    "\t\tON (department_manager.dept_no = departments.dept_no)\n",
    "\tINNER JOIN employees\n",
    "\t\tON (department_manager.emp_no = employees.emp_no);\n",
    "\t\n",
    "\t\n",
    "--List the department of each employee with the following information: employee number, \n",
    "--last name, first name, and department name.\n",
    "SELECT employees.emp_no,\n",
    "       employees.last_name,\n",
    "       employees.first_name,\n",
    "       departments.dept_name\n",
    "FROM employees \n",
    "    INNER JOIN department_employee\n",
    "    ON employees.emp_no = department_employee.emp_no\n",
    "inner join departments\n",
    "on department_employee.dept_no = departments.dept_no;\n",
    "\n",
    "\n",
    "--List first name, last name, and sex for employees \n",
    "--whose first name is \"Hercules\" and last names begin with \"B.\"\n",
    "SELECT employees.first_name,\n",
    "\t   employees.last_name,\n",
    "\t   employees.sex\n",
    "FROM employees\n",
    "WHERE employees.first_name = 'Hercules' \n",
    "AND employees.last_name LIKE 'B%';\n",
    "\n",
    "\n",
    "--List all employees in the Sales department, including their employee number,\n",
    "--last name, first name, and department name.\n",
    "SELECT employees.emp_no,\n",
    "\t   employees.last_name,\n",
    "\t   employees.first_name,\n",
    "\t   departments.dept_name\n",
    "FROM employees\n",
    "LEFT JOIN department_employee \n",
    "ON department_employee.emp_no = employees.emp_no\n",
    "LEFT JOIN departments\n",
    "ON department_employee.dept_no=departments.dept_no\n",
    "WHERE dept_name = 'Sales';\n",
    "\n",
    "\n",
    "--List all employees in the Sales and Development departments, including \n",
    "--their employee number, last name, first name, and department name.\n",
    "SELECT employees.emp_no,\n",
    "\t   employees.last_name,\n",
    "\t   employees.first_name,\n",
    "\t   departments.dept_name\n",
    "FROM employees\n",
    "LEFT JOIN department_employee\n",
    "ON department_employee.emp_no=  employees.emp_no\n",
    "LEFT JOIN departments\n",
    "ON department_employee.dept_no = departments.dept_no\n",
    "WHERE dept_name = 'Sales' OR  dept_name='Development'; \n",
    "\n",
    "\n",
    "--In descending order, list the frequency count of employee \n",
    "--last names, i.e., how many employees share each last name.\n",
    "SELECT COUNT (DISTINCT employees.last_name)\n",
    "FROM employees;"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
